### PR TITLE
Fix plugin for use with Serverless 1.12.x

### LINKED ISSUE #6: Serverless Error Invalid template resource property as of serverless version 1.12.1
Serverless Error ---------------------------------------
 
     Invalid template resource property '__deployment__'

With the recent deployment of 1.12.1, the current config doesn't seem to work.

### PR DESCRIPTION
**Pull request by ajkerr**
Changes were made in Serverless 1.12 that changed how package/deploy work. This PR is designed to fix #6.

Based on some discussion towards the end of https://github.com/serverless/serverless/pull/3344, it appears that the lifecycle has changed such that you can still modify this.serverless.service.provider.compiledCloudFormationTemplate to make in-memory changes to the template, but modifying other things, such as this.serverless.service.resources.Resources, has no effect.

This fix seems to work. The only visible change that I could see was that the changes are not persisted to disk, but they *do* get uploaded and updated in CloudFormation.

There may be a better way/place to do this (perhaps by using new package lifecycle events), but this does seem to get the plugin working again.

### CODE REVIEW

**Comment by ajkerr** [comment]
I've made another commit that basically restored the original code (except for the classname typo correction), and changes the hook from `before:deploy:deploy` to `before:aws:package:finalize:mergeCustomProviderResources`.

This allows us to modify the `this.serverless.service.resources.Resources` object _before_ it get merged into the compiled CloudFormation template.

The plugin now seems to work as it did before, although it's probably not compatible with pre-1.12 versions of Serverless.

**Comment by jacob-meacham** [comment]
Looks good to me, thanks!

**Comment by ajkerr** [comment]
Great, thanks for merging! Would it be possible for you to push a new version to npm soon?

**Comment by jacob-meacham** [comment]
@ajkerr I just published 1.0.0 to NPM. Thanks!

**Pull request merged**
